/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";

export function Bonsai(props) {
  const { nodes, materials } = useGLTF("/static/bonsai.glb");
  return (
    <group {...props} dispose={null}>
      <group scale={0.02}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.node_id33.geometry}
          material={materials["54"]}
          position={[-132.45, -214.95, 322.18]}
          scale={62.56}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.node_id35.geometry}
          material={materials["55"]}
          position={[-132.45, -214.95, 322.18]}
          scale={62.56}
        />
      </group>
    </group>
  );
}

useGLTF.preload("/static/bonsai.glb");
