/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";

export function Cerbero(props) {
  const { nodes, materials } = useGLTF("/static/cerbero.glb");
  return (
    <group {...props} dispose={null}>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.cerbero.geometry}
        material={nodes.cerbero.material}
        position={[0, 142.38, 0]}
        rotation={[Math.PI / 2, 0, -Math.PI / 2]}
      />
    </group>
  );
}

useGLTF.preload("/static/cerbero.glb");
