/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";

export function Gargoyle(props) {
  const { nodes, materials } = useGLTF("/static/gargoyle .glb");
  return (
    <group {...props} dispose={null}>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Gargoyle_Statue.geometry}
        material={materials["Gargoyle Statue Material"]}
        position={[0, 0, 0.04]}
        rotation={[Math.PI / 2, 0, 0]}
        scale={0.95}
      />
    </group>
  );
}

useGLTF.preload("/static/gargoyle .glb");
