/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";

export function Hercules(props) {
  const { nodes, materials } = useGLTF("/static/hercules.glb");
  return (
    <group {...props} dispose={null}>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Group34765.geometry}
        material={nodes.Group34765.material}
        position={[1.14, 0.33, 0.45]}
        rotation={[Math.PI / 2, 0, -1.17]}
        scale={0.01}
      />
    </group>
  );
}

useGLTF.preload("/static/hercules.glb");
