/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";

export function Libro(props) {
  const { nodes, materials } = useGLTF("/static/libro.glb");
  return (
    <group {...props} dispose={null}>
      <group rotation={[Math.PI / 2, 0, 0]} scale={0.01}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Candle.geometry}
          material={materials.phongE5}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Malla003.geometry}
          material={materials.phongE2}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Malla003_1.geometry}
          material={materials.phong3}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Scroll.geometry}
          material={materials.phongE3}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Book.geometry}
          material={materials.phongE6}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Feather1.geometry}
          material={materials.phongE7}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Feather2.geometry}
          material={materials.phongE7}
        />
      </group>
    </group>
  );
}

useGLTF.preload("/static/libro.glb");
