/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";

export function Mesa(props) {
  const { nodes, materials } = useGLTF("/static/mesa.glb");
  return (
    <group {...props} dispose={null}>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.table.geometry}
        material={materials["Material.001"]}
        position={[0, 5.48, 0]}
        rotation={[Math.PI / 2, 0, Math.PI / 2]}
        scale={0.22}
      />
    </group>
  );
}

useGLTF.preload("/static/mesa.glb");
