/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
author: LZ Creation (https://sketchfab.com/jmch)
license: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
source: https://sketchfab.com/3d-models/zeus-782f99eadca041b8b52d9e0a2c6f4e3f
title: Zeus
*/

import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";

export function Zeus(props) {
  const { nodes, materials } = useGLTF("/static/zeus.glb");
  return (
    <group {...props} dispose={null}>
      <group
        position={[-1.01, -20.63, 19.62]}
        rotation={[-Math.PI, -Math.PI / 2, 0]}
      >
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_5.geometry}
          material={materials.Zeus_300k_ZR_Material_u2_v1}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_2.geometry}
          material={materials.Zeus_300k_ZR_Material_u1_v1}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_3.geometry}
          material={materials.Zeus_300k_ZR_Material_u1_v1}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_4.geometry}
          material={materials.Zeus_300k_ZR_Material_u1_v1}
        />
      </group>
    </group>
  );
}

useGLTF.preload("/static/zeus.glb");
