// /*
// Auto-generated by: https://github.com/pmndrs/gltfjsx
// */

// import React, { useRef } from "react";
// import { useGLTF } from "@react-three/drei";
// import { useRouter } from "next/navigation";

// export function Coliseo(props) {
//   const { nodes, materials } = useGLTF("/static/coliseo.glb");
//   const router = useRouter()
//   return (
//     <group {...props} dispose={null} onClick={()=>{router.push('/arquitectura')}}>
//       <mesh
//         castShadow
//         receiveShadow
//         geometry={nodes.Cube001.geometry}
//         material={materials["Material.001"]}
//         position={[3.75, 3.56, 1.94]}
//         scale={-0.31}
//       />
//       <mesh
//         castShadow
//         receiveShadow
//         geometry={nodes.Cube.geometry}
//         material={materials.Material}
//       />
//       <mesh
//         castShadow
//         receiveShadow
//         geometry={nodes["10064_colosseum_v1_Iteration0"].geometry}
//         material={materials["10064_colosseum"]}
//         position={[3.75, 3.56, 1.94]}
//         scale={0.01}
//       />
//     </group>
//   );
// }

// useGLTF.preload("/static/coliseo.glb");

/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef, useState } from "react";
import { useGLTF } from "@react-three/drei";
import { useRouter } from "next/navigation";
import { useThree } from "@react-three/fiber";
import { Box,CircularProgress } from '@mui/material';
import { Html } from '@react-three/drei';

export function Coliseo(props) {
  const { nodes, materials } = useGLTF("/static/coliseo.glb");
  const router = useRouter()
  const { gl } = useThree();
  

  const handleMouseEnter = () => {
    gl.domElement.style.cursor = "pointer";
  };

  const handleMouseLeave = () => {
    gl.domElement.style.cursor = "auto";
  };

  const handleClick = () => {
    props.setIsLoading(true);
    router.push("/arquitectura");
  };

  return (
    <group 
      {...props} 
      dispose={null}
      onClick={handleClick}
      onPointerEnter={handleMouseEnter}
      onPointerLeave={handleMouseLeave}
    >
      <mesh
        castShadow
        receiveShadow
        geometry={nodes["10064_colosseum_v1_Iteration0"].geometry}
        material={materials["10064_colosseum"]}
        rotation={[0, 1.57, 0]}
        scale={0.005}
      />
    </group>
  );
}

useGLTF.preload("/static/coliseo.glb");



