/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useState, useRef } from "react";
import { useGLTF } from "@react-three/drei";
import { useRouter } from "next/navigation";
import { useThree } from "@react-three/fiber";

export function Derecho(props) {
  const { nodes, materials } = useGLTF("/static/leyes.glb");
  const router = useRouter()
  const { gl } = useThree();

  const handleMouseEnter = () => {
    gl.domElement.style.cursor = "pointer";
  };

  const handleMouseLeave = () => {
    gl.domElement.style.cursor = "auto";
  };

  const handleClick = () => {
    router.push("/cultura");
  };

  return (
    <group {...props} 
    dispose={null}
    onClick={handleClick}
    onPointerEnter={handleMouseEnter}
    onPointerLeave={handleMouseLeave}
    >
      <group scale={0.008}>
        <group
          position={[-218.72, -65.9, 256]}
          rotation={[Math.PI / 2, 0, 0]}
          scale={7.85}
        >
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.node_id7.geometry}
            material={materials["36"]}
          />
        </group>
        <group
          position={[-180.39, 39.09, 259.07]}
          rotation={[Math.PI / 2, -0.29, 0]}
          scale={7.85}
        >
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.node_id12.geometry}
            material={materials["37"]}
          />
        </group>
        <group
          position={[28.67, -10.24, 259.07]}
          rotation={[Math.PI / 2, -0.29, 0]}
          scale={7.85}
        >
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.node_id16.geometry}
            material={materials["38"]}
          />
        </group>
        <group
          position={[-180.99, 39.26, 259.07]}
          rotation={[Math.PI / 2, -0.29, 0]}
          scale={[8, 8, 7.76]}
        >
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.node_id20.geometry}
            material={materials["39"]}
          />
        </group>
      </group>
    </group>
  );
}

useGLTF.preload("/static/leyes.glb");
