/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";
import { useRouter } from "next/navigation";
import { useThree } from "@react-three/fiber";

export function Statue(props) {
  const { nodes, materials } = useGLTF("/static/estatua.glb");
  const router = useRouter()
  const { gl } = useThree();

  const handleMouseEnter = () => {
    gl.domElement.style.cursor = "pointer";
  };

  const handleMouseLeave = () => {
    gl.domElement.style.cursor = "auto";
  };

  const handleClick = () => {
    router.push("/cultura");
  };

  return (
    <group
      {...props}
      dispose={null}
      onClick={handleClick}
      onPointerEnter={handleMouseEnter}
      onPointerLeave={handleMouseLeave}
    >
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.defaultobject.geometry}
        material={materials.DefaultMaterial}
      />
    </group>
  );
}

useGLTF.preload("/static/estatua.glb");
