/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef,useState } from "react";
import { useGLTF } from "@react-three/drei";
import { useRouter } from "next/navigation";
import { useThree } from "@react-three/fiber";
import { Box,CircularProgress } from '@mui/material';
import { Html } from '@react-three/drei';

export function Statue({setIsLoading},props) {
  const { nodes, materials } = useGLTF("/static/mars.glb");
  const router = useRouter()
  const { gl } = useThree();

  const handleMouseEnter = () => {
    gl.domElement.style.cursor = "pointer";
  };

  const handleMouseLeave = () => {
    gl.domElement.style.cursor = "auto";
  };

  const handleClick = () => {
    setIsLoading(true);
    router.push("/arte");
  };

  return (
    <group
      {...props}
      dispose={null}
      onClick={handleClick}
      onPointerEnter={handleMouseEnter}
      onPointerLeave={handleMouseLeave}
    >
      <mesh
        castShadow
        receiveShadow
        onClick={handleClick}
        geometry={nodes.mars.geometry}
        material={materials["Material.001"]}
        position={[0, 2.5, 1.1]}
        rotation={[-Math.PI / 2, 0, Math.PI / 2]}
      />
      {/* <Html>
          {isLoading && ( 
              <Box sx={{position:'fixed',top: 0, left: 0, width: '100vw', height: '100vh', backgroundColor: 'rgba(0, 0, 0, 0.7)', display: 'flex', alignItems: 'center', justifyContent: 'center' }}>
                <CircularProgress color="primary" />
              </Box>
          )}    
      </Html> */}
    </group>
  );
}

useGLTF.preload("/static/mars.glb");
