/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";
import { useRouter } from "next/navigation";
import { useThree } from "@react-three/fiber";

export function Statue(props) {
  const { nodes, materials } = useGLTF("/static/mars.glb");
  const router = useRouter()
  const { gl } = useThree();

  const handleMouseEnter = () => {
    gl.domElement.style.cursor = "pointer";
  };

  const handleMouseLeave = () => {
    gl.domElement.style.cursor = "auto";
  };

  const handleClick = () => {
    router.push("/arte");
  };

  return (
    <group
      {...props}
      dispose={null}
      onClick={handleClick}
      onPointerEnter={handleMouseEnter}
      onPointerLeave={handleMouseLeave}
    >
      <mesh
        castShadow
        receiveShadow
        onClick={handleClick}
        geometry={nodes.mars.geometry}
        material={materials["Material.001"]}
        position={[0, 2.5, 1.1]}
        rotation={[-Math.PI / 2, 0, Math.PI / 2]}
      />
    </group>
  );
}

useGLTF.preload("/static/mars.glb");
