/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";

export function Suelo(props) {
  const { nodes, materials } = useGLTF("/static/suelo.glb");
  return (
    <group {...props} dispose={null}>
      <mesh
        // castShadow
        receiveShadow
        geometry={nodes.Plano.geometry}
        material={materials["Material.001"]}
        scale={[26.457, 1.2, 26.457]}
      />
    </group>
  );
}

useGLTF.preload("/static/suelo.glb");
