/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";

export function Bush(props) {
  const { nodes, materials } = useGLTF("/static/bush.glb");
  return (
    <group {...props} dispose={null}>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Плоскость002.geometry}
        material={materials.Материал}
        position={[3.86, 0.76, -0.01]}
        rotation={[2.21, -0.4, -1.89]}
        scale={[0.1, 0.33, 0.33]}
      />
    </group>
  );
}

useGLTF.preload("/static/bush.glb");
