/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";

export function Tree(props) {
  const { nodes, materials } = useGLTF("/static/tree.glb");
  return (
    <group {...props} dispose={null}>
      <group scale={0.001}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.node_id35.geometry}
          material={materials["53"]}
          position={[10.208, -194.172, 256.33]}
          scale={12.931}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.node_id37.geometry}
          material={materials["54"]}
          position={[10.208, -194.172, 256.33]}
          scale={12.931}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.node_id39.geometry}
          material={materials["55"]}
          position={[10.208, -194.172, 256.33]}
          scale={12.931}
        />
      </group>
    </group>
  );
}

useGLTF.preload("/static/tree.glb");
